### ISSUE TITLE
Start off early and get documentation done.

### ISSUE THREAD

**Issue by TheGogy** [Tom-Pecher/RL-CW#4]
We need to agree on a solid coding style and documentation style.

Given that we are using C++, I propose we use the [LLVM](https://llvm.org/docs/CodingStandards.html) coding standards for how we lay out the code, and [Doxygen](https://www.doxygen.nl/) for code documentation. I am happy to write all of this from scratch. I have also found a good Doxygen theme [here](https://jothepro.github.io/doxygen-awesome-css/index.html). 

If instead we would like to use Rust - which we can do - then it would also be possible to set up alternative documentation methods which we can discuss then.

**Comment by Tom-Pecher** [comment]
Changed to Python, will use OpenAI Gymnasium
